MovieRental1/MovieRental1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieRental1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Overdue()
        {
            ViewBag.Message = "Your overdue page.";

            return View();
        }
    }
}

MovieRental1/MovieRental1/Controllers/RentalRecordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieRental1;

namespace MovieRental1.Controllers
{
    public class RentalRecordsController : Controller
    {
        private MovieRentalEntities db = new MovieRentalEntities();

        // GET: RentalRecords
        public ActionResult Index()
        {
            var rentalRecords = db.RentalRecords.Include(r => r.Movy);
            return View(rentalRecords.ToList());
        }

        // GET: RentalRecords/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalRecord rentalRecord = db.RentalRecords.Find(id);
            if (rentalRecord == null)
            {
                return HttpNotFound();
            }
            return View(rentalRecord);
        }

        // GET: RentalRecords/Create
        public ActionResult Create()
        {
            ViewBag.MovieID = new SelectList(db.Movies, "MovieID", "MovieName");
            return View();
        }

        // POST: RentalRecords/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RentalID,MovieID,CustomerID,RentalDate,DueDate,ReturnDate")] RentalRecord rentalRecord)
        {
            if (ModelState.IsValid)
            {
                db.RentalRecords.Add(rentalRecord);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MovieID = new SelectList(db.Movies, "MovieID", "MovieName", rentalRecord.MovieID);
            return View(rentalRecord);
        }

        // GET: RentalRecords/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalRecord rentalRecord = db.RentalRecords.Find(id);
            if (rentalRecord == null)
            {
                return HttpNotFound();
            }
            ViewBag.MovieID = new SelectList(db.Movies, "MovieID", "MovieName", rentalRecord.MovieID);
            return View(rentalRecord);
        }

        // POST: RentalRecords/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RentalID,MovieID,CustomerID,RentalDate,DueDate,ReturnDate")] RentalRecord rentalRecord)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rentalRecord).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MovieID = new SelectList(db.Movies, "MovieID", "MovieName", rentalRecord.MovieID);
            return View(rentalRecord);
        }

        // GET: RentalRecords/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalRecord rentalRecord = db.RentalRecords.Find(id);
            if (rentalRecord == null)
            {
                return HttpNotFound();
            }
            return View(rentalRecord);
        }

        // POST: RentalRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RentalRecord rentalRecord = db.RentalRecords.Find(id);
            db.RentalRecords.Remove(rentalRecord);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieRental1/MovieRental1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MovieRental1/MovieRental1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MovieRental1/MovieRental1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Movie Rentals</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Rent A Movie</h2>
        <p>@Html.ActionLink("Movies", "Index", "Movies")</p>
    </div>
    <div class="col-md-4">
        <h2>Return Movies</h2>
        <p>@Html.ActionLink("Records", "Index", "RentalRecords")</p>
    </div>
    <div class="col-md-4">
        <h2>View Overdue movies</h2>
        <p>@Html.ActionLink("Overdue", "Overdue", "Home")</p>
    </div>
</div>

MovieRental1/MovieRental1/Views/Home/Overdue.cshtml
@{
    ViewBag.Title = "Overdue";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Overdue</h2>
@{
    MovieRentalEntities db = new MovieRentalEntities();

    var CertainRentals = from c in db.RentalRecords
                         join o in db.Movies
                         on c.MovieID equals o.MovieID
                         where c.DueDate < DateTime.Today
                         select new
                         {
                             Ren = c.DueDate,
                             Den = o.MovieName
                         };


    <table style="border:2px solid Blue">
        <tr>
            <th style="border:2px solid Blue">Movie Name</th>
            <th style="border:2px solid Red">Due Date</th>
        </tr>
        @foreach (var c in CertainRentals)
        {
        <tr style="border:2px solid Blue">
            <td style="border:2px solid Blue">@c.Den</td>
            <td style="border:2px solid Red">@String.Format("{0:MM/dd/yy}",@c.Ren)</td>
        </tr>
        }
    </table>
}